version: "3.5"
services:
  akademie:
    image: mindhochschulnetzwerk/akademie
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik
      - traefik.http.routers.akademie.entrypoints=websecure
      - traefik.http.routers.akademie.rule=${HOST_RULE}
      - traefik.http.routers.akademie.middlewares=secheader@file
    networks:
      - akademie
      - traefik

networks:
  akademie:
    name: akademie
  traefik:
    name: traefik
    external: true
